#!/bin/ksh

# Configures and builds googletest on OpenBSD 6.4.
# Version numbers correspond to the packages installed.

set -eux

export AUTOMAKE_VERSION=1.15
export AUTOCONF_VERSION=2.69

autoreconf -fvi
automake --add-missing
autoconf
./configure CC=/usr/bin/cc CXX=/usr/bin/cc CPP='/usr/bin/cc -E'
gmake
